### 장르 목록
GET http://localhost:8080/genres

### 장르 추가 (같은 장르 추가 시 409 에러 반환)
POST http://localhost:8080/genres
Content-Type: application/json

{"name":"여행에세이123"}

### 책 생성
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "테스트 책",
  "author": "홍길동",
  "content": "내용입니다",
  "genreId": 1
}

### 책 상세
GET http://localhost:8080/books/1

### 책 수정 (장르 변경)
PATCH http://localhost:8080/books/1
Content-Type: application/json

{"genreId": 9}

### 장르별 도서
GET http://localhost:8080/genres/9/books

### 책 검색
GET http://localhost:8080/books/search?keyword=해리

### 책 삭제
GET http://localhost:8080/books/999