server:
  port: 8080

spring:
  application:
    name: bookapp

  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: mini5
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

cloudinary:
  cloud-name: dyi23dc8x
  api-key: 179344155233932
  api-secret: bhPiS2v-IqIIIFtttOSq6kfyrU4